spring.application.name=banking-backend
# ===== CONFIGURATION BASE DE DONNÉES =====
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=Joetak&4
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== CONFIGURATION SERVEUR =====
server.port=8081

# ===== LOGGING =====
logging.level.com.banking=DEBUG
logging.level.org.springframework.security=DEBUG

# ===== SPRING SECURITY =====
spring.security.user.name=admin
spring.security.user.password=admin123

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:3000,http://localhost:3001,http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joellanaurlays@gmail.com
spring.mail.password=Joetak&4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Solution temporaire pour LazyInitializationException
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true